### ISSUE TITLE
OnlineFriendCount shows blank screen

### ISSUE THREAD

**Issue by RobinRMC** [Zerthox/BetterDiscord-Plugins#131]
Title says it all.

Reproduce:

1. Install OnlineFriendCount
2. Enable OnlineFriendCount
3. Close Discord through tray
4. Open Discord
5. Observe

**Comment by Zerthox** [comment]
Are you on stable Discord? Which version of OnlineFriendCount are you running? Which other plugins do you have running? Can you check the developer console for errors and output from the plugin?

**Comment by RobinRMC** [comment]
Stable Discord. Latest version of OnlineFriendCount. Other plugins: too many. I've checked developer console before, but I'll check again tomorrow. I don't have enough time to check it right now.

**Comment by Zerthox** [comment]
Latest version of OnlineFriendCount means which version number? I am asking because the latest version on the site is not the latest version available (2.2.1 vs 3.1.0). If you don't want to list all other plugins, please verify it's not a compatibility issue by removing every other plugin and running OnlineFriendCount on its own.

**Comment by RobinRMC** [comment]
I always install plugins from GitHub, so it's the latest version.
The problem doesn't seem to occur when I remove Address and DevTools by [LoneWeeb](https://github.com/Tharki-God/BetterDiscordPlugins).

**Comment by Zerthox** [comment]
Looking at the code, both of these plugins have the same bug my plugins used to have (possibly copied the way I force update). This is something that needs to be fixed on their side.
Note that some of the plugins in that repo put your account at risk of termination when used.

**Comment by RobinRMC** [comment]
@Zerthox Thanks for the info. I am careful using risky plugins and I never spam the API, so I should be fine. Thanks for the warning though!

**Comment by Tharki-God** [comment]
consider changinging your code to this and it will add capability for my plugins ```
const forceFullRerender = (fiber) => new Promise((resolve) => {
    const owner = findOwner(fiber);
    if (owner) {
        const { stateNode } = owner;
        if (stateNode?.render?.name ==  "forceRerender") return;
        instead(stateNode, "render", ({context}) => null, { once: true, silent: true });
        stateNode.forceUpdate(() => stateNode.forceUpdate(() => resolve(true)));
    }
    else {
        resolve(false);
    }
});
```

**Comment by Zerthox** [comment]
This check would only work as long as **all** plugins adhere to it and no plugin patches `render` for other purposes than force updating. If either of those conditions does not hold, you end up still having the same race condition.

Using BD's inbuillt patcher is the more suitable solution, since it ensures compatibility as long as every pugin goes through it.

**Comment by Tharki-God** [comment]
Yeah changed my plugins to use it
