### ISSUE TITLE
[VoiceEvents] Speech Synthesis Voices not available on ubuntu.

### ISSUE THREAD

**Issue by ivenspontes** [Zerthox/BetterDiscord-Plugins#55]
i get this error message: Electron does not have any speech synthesis voices available on your system.

ubuntu 20.04

**Comment by Zerthox** [comment]
Speech synthesis voices being unavailable is either because there is no speech synthesis installed on your system or it is installed in a way that Chromium/Electron is unable to find or make use of it. It's an issue with your system or Chromium/Electron, not with the plugin itself.

This is likely a similar problem to #27, there might be a few helpful infos there.

**Comment by ivenspontes** [comment]
> Try running discord using the command: `discord --enable-speech-dispatcher`

works fine, i change the .desktop file to Exec=sh -c "discord --enable-speech-dispatcher"
